language: node_js
node_js: "10"
os:
- windows
- osx

osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

branches:
  only:
  - master
  - ci
  - /^v\d+\.\d+\.\d+/

install:
  - npm install
  - npm update

script:
  - npm run lint
  - if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi

config: {
  forge: {
    make_targets: {
      win32: [
        "squirrel"
      ],
      darwin: [
        "zip"
      ],
    },
    electronPackagerConfig: {
      packageManager: "npm"
    },
    electronWinstallerConfig: {
      "name": "Adobe Plugin Installer"
    },
    windowsStoreConfig: {
      packageName: "Adobe Plugin Installer",
      name: "dobe Plugin Installer"
    },
    github_repository: {
      owner: "",
      name: ""
    }
  }
}
